<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rotors_description)/urdf/manipulator_snippets.xacro" />

  <xacro:property name="r1_width" value="0.05"/>
  <xacro:property name="r1_height" value="0.01"/>
  <xacro:property name="r1_length" value="0.24"/>

  <xacro:property name="r2_width" value="0.05"/>
  <xacro:property name="r2_height" value="0.008"/>
  <xacro:property name="r2_length" value="0.35"/>

  <xacro:property name="r3_width" value="0.05"/>
  <xacro:property name="r3_height" value="0.01"/>
  <xacro:property name="r3_length" value="0.16"/>

  <xacro:property name="end_effector_length" value="0.12"/>
  <xacro:property name="end_effector_radius" value="0.03"/>


  <xacro:property name="r3_frame">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="r3_inertial">
    <mass value="0.002"/>
    <inertia ixx="0.0031" ixy="0.0" ixz="0.0"
    iyy="0.0061" iyz="0.0"
    izz="0.0081"/>
  </xacro:property>

  <xacro:property name="r3_geometry">
    <geometry>
       <box size="${r3_length} ${r3_width} ${r3_height}"/>
    </geometry>
  </xacro:property>

  <xacro:property name="r3_material">
    <material name="orange"/>
  </xacro:property>

  <xacro:property name="r2_frame">
    <origin xyz="${r2_length/2} 0 0" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="r2_inertial">
    <mass value="0.0025"/>
    <inertia ixx="0.0021" ixy="0.0" ixz="0.0"
    iyy="0.0031" iyz="0.0"
    izz="0.0081"/>
  </xacro:property>

  <xacro:property name="r2_geometry">
    <geometry>
       <box size="${r2_length} ${r2_width} ${r2_height}"/>
    </geometry>
  </xacro:property>

  <xacro:property name="r2_material">
    <material name="orange"/>
  </xacro:property>

  <xacro:property name="r1_frame">
    <origin xyz="${r1_length/2} 0 0" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="r1_inertial">
    <mass value="0.0025"/>
    <inertia ixx="0.0031" ixy="0.0" ixz="0.0"
    iyy="0.0031" iyz="0.0"
    izz="0.0081"/>
  </xacro:property>

  <xacro:property name="r1_geometry">
    <geometry>
       <box size="${r1_length} ${r1_width} ${r1_height}"/>
    </geometry>
  </xacro:property>

  <xacro:property name="r1_material">
    <material name="orange"/>
  </xacro:property>

  <xacro:property name="end_effector_frame">
    <origin xyz="${end_effector_length/2} 0 0" rpy="0 ${PI/2} 0"/>
  </xacro:property>

  <xacro:property name="end_effector_inertial">
    <mass value="0.02"/>
    <inertia ixx="0.0031" ixy="0.0" ixz="0.0"
    iyy="0.0051" iyz="0.0"
    izz="0.0081"/>
  </xacro:property>

  <xacro:property name="end_effector_geometry">
    <geometry>
       <cylinder length="${end_effector_length}"  radius="${end_effector_radius}"/>
    </geometry>
  </xacro:property>

<!-- macro used to define a closed chain -->
  <xacro:macro name="closed_chain_macro"
    params="namespace parent_link *origin">

    <xacro:revolute_joint_macro
      namespace="${namespace}"
      joint_name="${namespace}/pitching"
      parent_link="${parent_link}"
      child_link="${namespace}/r3"
      axis="1 0 0"
      friction="0"
      damping="0.1">
      <xacro:insert_block name="origin" />
    </xacro:revolute_joint_macro>

    <!-- <joint name="${namespace}/fixed_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child  link="${namespace}/r3"/>
      <xacro:insert_block name="origin" />
    </joint> -->

  <!-- Here we define base link of closed kinematic chain -->
  <link name="${namespace}/r3">
   <collision>
     <xacro:insert_block name="r3_frame"/>
     <xacro:insert_block name="r3_geometry"/>
    </collision>

    <visual>
      <xacro:insert_block name="r3_frame"/>
      <xacro:insert_block name="r3_geometry"/>
    </visual>

    <inertial>
      <xacro:insert_block name="r3_frame"/>
      <xacro:insert_block name="r3_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/r1_left">
   <collision>
     <xacro:insert_block name="r1_frame"/>
     <xacro:insert_block name="r1_geometry"/>
    </collision>

    <visual>
      <!-- <xacro:insert_block name="r1_frame"/> -->
      <!-- <xacro:insert_block name="r1_geometry"/> -->
      <!-- <origin xyz="0.03 0.115 -0.005" rpy="1.57 0 -0.3"/> -->
      <origin xyz="${r1_length/2} 0 -0.004" rpy="1.57 0 0"/>

      <geometry>
          <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R1_v2.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r1_frame"/>
      <xacro:insert_block name="r1_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/r1_right">
   <collision>
     <xacro:insert_block name="r1_frame"/>
     <xacro:insert_block name="r1_geometry"/>
    </collision>

    <visual>
      <!-- <xacro:insert_block name="r1_frame"/>
      <xacro:insert_block name="r1_geometry"/> -->
      <!-- <origin xyz="0.03 -0.115 0.008" rpy="-1.57 0 0.3"/> -->
       <origin xyz="${r1_length/2} 0 0.012" rpy="-1.57 0 0"/>
      <geometry>
          <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R1_v2.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r1_frame"/>
      <xacro:insert_block name="r1_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/r2_left">
   <collision>
     <xacro:insert_block name="r2_frame"/>
     <xacro:insert_block name="r2_geometry"/>
    </collision>

    <visual>
      <!-- <xacro:insert_block name="r2_frame"/>
      <xacro:insert_block name="r2_geometry"/> -->
      <origin xyz="${r2_length/2} 0 -0.026" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R2_v2.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r2_frame"/>
      <xacro:insert_block name="r2_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/r2_right">
   <collision>
     <xacro:insert_block name="r2_frame"/>
     <xacro:insert_block name="r2_geometry"/>
    </collision>

    <visual>
      <!-- <xacro:insert_block name="r2_frame"/>
      <xacro:insert_block name="r2_geometry"/> -->
      <origin xyz="${r2_length/2} 0 -0.005" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R2_v2.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r2_frame"/>
      <xacro:insert_block name="r2_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/end_effector">
   <collision>
     <xacro:insert_block name="end_effector_frame"/>
     <xacro:insert_block name="end_effector_geometry"/>
    </collision>

    <visual>
      <!-- <xacro:insert_block name="end_effector_frame"/>
      <xacro:insert_block name="end_effector_geometry"/> -->
      <origin xyz="0 0 -0.015" rpy="1.57 0 1.2"/>
      <geometry>
          <mesh filename="package://rotors_description/meshes/delta_arm_meshes/end_effector_plate.dae" scale="0.001 0.001 0.001" />
      </geometry>

    </visual>

    <inertial>
      <xacro:insert_block name="end_effector_frame"/>
      <xacro:insert_block name="end_effector_inertial"/>
    </inertial>
  </link>

<!-- Define joints -->
  <xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/left_1"
    parent_link="${namespace}/r3"
    child_link="${namespace}/r1_left"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${r3_length/2} 0 -0.01" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>

  <xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/right_1"
    parent_link="${namespace}/r3"
    child_link="${namespace}/r1_right"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${-r3_length/2} 0 -0.015" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>

  <xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/left_2"
    parent_link="${namespace}/r1_left"
    child_link="${namespace}/r2_left"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${r1_length} 0 0.015" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>

  <xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/right_2"
    parent_link="${namespace}/r1_right"
    child_link="${namespace}/r2_right"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${r1_length} 0 0.015" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>

  <xacro:gazebo_revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/closing"
    parent_link="${namespace}/r2_left"
    child_link="${namespace}/r2_right"
    pose="${r2_length} 0 0 0 0 0"
    axis="0 0 1"
    friction="0"
    damping="0.1"
    spring_reference="0"
    spring_stiffness="0"
    lower_limit="-1e+16"
    upper_limit="1e+16"
    effort_limit="1000">
  </xacro:gazebo_revolute_joint_macro>

  <xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/end_effector"
    parent_link="${namespace}/r2_left"
    child_link="${namespace}/end_effector"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${r2_length} 0 0" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>

  <!-- Attach actuators -->

  <xacro:property name="generic_servo_inertial">
    <inertial>
    <mass value="0.02"/>
    <inertia ixx="0.001" ixy="0.0" ixz="0.0"
    iyy="0.001" iyz="0.0"
    izz="0.001"/>
  </inertial>
  </xacro:property>

 <xacro:servo_motor_macro
   namespace="${namespace}"
   motor_name="motor_left"
   parent_link="${namespace}/r3"
   actuated_joint="${namespace}/left_1"
   motor_model="generic_servo1"
   maxTorque="2"
   noLoadSpeed="0.11"
   Kp="30.0"
   Kd="0.05"
   Ki="0.40"
   minAngle="${-PI}"
   maxAngle="${PI}"
   enable_visual="true"
   visual_scale="1"
   color="Blue">
   <origin xyz="${r3_length/2} 0 0.02" rpy="-1.57 0 0"/>
   <xacro:insert_block name="generic_servo_inertial"/>
 </xacro:servo_motor_macro>

 <xacro:servo_motor_macro
   namespace="${namespace}"
   motor_name="motor_right"
   parent_link="${namespace}/r3"
   actuated_joint="${namespace}/right_1"
   motor_model="generic_servo2"
   maxTorque="2"
   noLoadSpeed="0.11"
   Kp="30.0"
   Kd="0.05"
   Ki="0.40"
   minAngle="${-PI}"
   maxAngle="${PI}"
   enable_visual="true"
   visual_scale="1"
   color="Red">
   <origin xyz="${-r3_length/2} 0 0.02" rpy="-1.57 0 0"/>
   <xacro:insert_block name="generic_servo_inertial"/>
 </xacro:servo_motor_macro>

 <xacro:servo_motor_macro
   namespace="${namespace}"
   motor_name="motor_end_effector"
   parent_link="${namespace}/r2_left"
   actuated_joint="${namespace}/end_effector"
   motor_model="generic_servo3"
   maxTorque="0.8"
   noLoadSpeed="0.11"
   Kp="10.0"
   Kd="0.05"
   Ki="0.40"
   minAngle="${-PI}"
   maxAngle="${PI}"
   enable_visual="false"
   visual_scale="1"
   color="Red">
   <origin xyz="${r2_length} 0 0.02" rpy="-1.57 0 0"/>
   <xacro:insert_block name="generic_servo_inertial"/>
 </xacro:servo_motor_macro>


 >

 <xacro:servo_motor_macro
   namespace="${namespace}"
   motor_name="motor_pitching"
   parent_link="${parent_link}"
   actuated_joint="${namespace}/pitching"
   motor_model="generic_servo0"
   maxTorque="2"
   noLoadSpeed="0.11"
   Kp="30.0"
   Kd="0.05"
   Ki="0.40"
   minAngle="${-PI}"
   maxAngle="${PI}"
   enable_visual="true"
   visual_scale="1"
   color="Red">
   <origin xyz="0 0 0.02" rpy="0 0 0"/>
   <xacro:insert_block name="generic_servo_inertial"/>
 </xacro:servo_motor_macro>


<!-- Initial configuration plugin -->
<gazebo>
  <plugin name="initial_configuration" filename="librotors_gazebo_robot_initial_configuration_plugin.so">
    <robotNamespace>${namespace}</robotNamespace>
 <initial_configuration>
   <config joint_name="left_1"  initial_position="0.3415"/>
   <config joint_name="left_2"  initial_position="2.2942"/>
   <config joint_name="right_1" initial_position="2.8001"/>
   <config joint_name="right_2" initial_position="-2.2942"/>
   <config joint_name="pitching" initial_position="0"/>
 </initial_configuration>
 <loop_closure_joints>
   <joint joint_name="closing"/>
 </loop_closure_joints>
 </plugin>
</gazebo>

</xacro:macro>
</robot>
