<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rotors_description)/urdf/manipulator_snippets.xacro" />

  <xacro:property name="link_radius" value="0.02"/>

  <xacro:property name="link1_length" value="0.296"/>
  <xacro:property name="link2_length" value="0.5"/>

  <xacro:property name="link0_center_to_center_length" value="0.1"/>

  <xacro:property name="link0_frame">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="link0_inertia">
    <mass value="0.001"/>
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
      iyy="0.0001" iyz="0.0"
      izz="0.0001"/>
    </xacro:property>

    <xacro:property name="link1_frame">
      <origin xyz="${link1_length/2} 0 0" rpy="3.14 0 0"/>
    </xacro:property>

    <xacro:property name="link1_inertia">
      <mass value="0.02"/>
      <inertia ixx="0.000948062" ixy="0.0" ixz="-0.001716204"
        iyy="0.00730949" iyz="0.0"
        izz="0.006364922"/>
      </xacro:property>

    <xacro:property name="link2_frame">
      <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
    </xacro:property>

    <xacro:property name="link2_inertia">
      <mass value="0.025"/>
      <inertia ixx="0.000229511" ixy="0.0" ixz="0.00000098"
        iyy="0.0018644679" iyz="0.0"
        izz="0.0018419229"/>
      </xacro:property>

          <!--
          #########################################################################################################################
          Dextar manipulator macro:
          #########################################################################################################################
        -->
        <xacro:macro name="dextar_manipulator_macro"
          params="namespace parent_link *origin">

          <joint name="mounting_joint" type="fixed">
            <parent link="${parent_link}"/>
            <child link="${namespace}/manipulator_base_link"/>
            <xacro:insert_block name="origin" />
          </joint>

          <!-- Here we define base link of closed kinematic chain -->
          <link name="${namespace}/manipulator_base_link">
            <inertial>
              <xacro:insert_block name="link0_frame"/>
              <xacro:insert_block name="link0_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/link1_1">
            <!-- <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/dextar_manipulator/link1_1.dae"/>
              </geometry>
            </collision> -->
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/dextar_manipulator/link1_1.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link1_frame"/>
              <xacro:insert_block name="link1_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/link1_2">
            <!-- <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/dextar_manipulator/link1_2.dae"/>
              </geometry>
            </collision> -->
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/dextar_manipulator/link1_2.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link1_frame"/>
              <xacro:insert_block name="link1_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/link2_1">
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/dextar_manipulator/link2_1.dae"/>
              </geometry>
            </collision>
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/dextar_manipulator/link2_1.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link2_frame"/>
              <xacro:insert_block name="link2_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/link2_2">
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/dextar_manipulator/link2_2.dae"/>
              </geometry>
            </collision>
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/dextar_manipulator/link2_2.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link2_frame"/>
              <xacro:insert_block name="link2_inertia"/>
            </inertial>
          </link>

          <!-- Define joints -->
          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_1"
            parent_link="${namespace}/manipulator_base_link"
            child_link="${namespace}/link1_1"
            axis="0 0 -1"
            friction="0"
            damping="0.1">
            <origin xyz="${-link0_center_to_center_length/2} 0 -0.005" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_2"
            parent_link="${namespace}/manipulator_base_link"
            child_link="${namespace}/link1_2"
            axis="0 0 -1"
            friction="0"
            damping="0.1">
            <origin xyz="${link0_center_to_center_length/2} 0 -0.005" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_3"
            parent_link="${namespace}/link1_1"
            child_link="${namespace}/link2_1"
            axis="0 0 -1"
            friction="0"
            damping="0.1">
            <origin xyz="${link1_length} 0 -0.0145" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_4"
            parent_link="${namespace}/link1_2"
            child_link="${namespace}/link2_2"
            axis="0 0 -1"
            friction="0"
            damping="0.1">
            <origin xyz="${link1_length} 0 -0.0145" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <xacro:gazebo_revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_5"
            parent_link="${namespace}/link2_1"
            child_link="${namespace}/link2_2"
            pose="${link2_length} 0 0 0 0 0"
            axis="0 0 -1"
            friction="0"
            damping="0.1"
            spring_reference="0"
            spring_stiffness="0"
            lower_limit="-1e+16"
            upper_limit="1e+16"
            effort_limit="1000">
          </xacro:gazebo_revolute_joint_macro>

      <!-- Attach actuators -->
      <xacro:property name="generic_servo_inertial">
        <inertial>
          <mass value="0.070"/>
          <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0"
            izz="0.001"/>
          </inertial>
        </xacro:property>

        <xacro:hebi_actuator_plugin
          namespace="${namespace}"
          motor_name="X5-4/M1"
          parent_link="${namespace}/manipulator_base_link"
          actuated_joint="delta_manipulator/joint_1"
          maxTorque="2"
          noLoadSpeed="0.11"
          Kp="30.0"
          Kd="0.05"
          Ki="0.40"
          minAngle="${-pi}"
          maxAngle="${pi}"
          measurement_divisor="1"
          measurement_delay="0"
          unknown_delay="0.0"
          noise_normal_angle="0.0"
          noise_normal_angular_velocity="0.0"
          noise_normal_torque="0.0"
          noise_uniform_angle="0.0"
          noise_uniform_angular_velocity="0.0"
          noise_uniform_torque="0.0"
          enable_visual="true"
          visual_scale="1"
          color="Red">
          <origin xyz="${link0_center_to_center_length/2} 0 0" rpy="3.14 0 1.57"/>
          <xacro:insert_block name="generic_servo_inertial"/>
        </xacro:hebi_actuator_plugin>

        <xacro:hebi_actuator_plugin
          namespace="${namespace}"
          motor_name="X5-4/M2"
          parent_link="${namespace}/manipulator_base_link"
          actuated_joint="delta_manipulator/joint_2"
          maxTorque="2"
          noLoadSpeed="0.11"
          Kp="30.0"
          Kd="0.05"
          Ki="0.40"
          minAngle="${-pi}"
          maxAngle="${pi}"
          measurement_divisor="1"
          measurement_delay="0"
          unknown_delay="0.0"
          noise_normal_angle="0.0"
          noise_normal_angular_velocity="0.0"
          noise_normal_torque="0.0"
          noise_uniform_angle="0.0"
          noise_uniform_angular_velocity="0.0"
          noise_uniform_torque="0.0"
          enable_visual="true"
          visual_scale="1"
          color="Red">
          <origin xyz="${-link0_center_to_center_length/2} 0 0" rpy="3.14 0 1.57"/>
          <xacro:insert_block name="generic_servo_inertial"/>
        </xacro:hebi_actuator_plugin>


        <!-- Initial configuration plugin -->
        <gazebo>
          <plugin name="initial_configuration" filename="librotors_gazebo_robot_initial_configuration_plugin.so">
            <robotNamespace>${namespace}</robotNamespace>
            <initial_configuration>
              <config joint_name="delta_manipulator/joint_1"  initial_position="-2.7342"/>
              <config joint_name="delta_manipulator/joint_3"  initial_position=" 1.8625"/>
              <config joint_name="delta_manipulator/joint_2" initial_position="-0.4074"/>
              <config joint_name="delta_manipulator/joint_4" initial_position="-1.8625"/>
            </initial_configuration>
            <loop_closure_joints>
              <joint joint_name="delta_manipulator/joint_5"/>
            </loop_closure_joints>
          </plugin>
        </gazebo>

        <!-- 6DoF shock absorber plugin -->
        <!-- <gazebo>
          <plugin name="6dof_shock_absorber" filename="librotors_gazebo_six_dof_shock_absorber_plugin.so">
            <robotNamespace>${namespace}</robotNamespace>
            <ParentLinkName>${parent_link} </ParentLinkName>
            <ChildLinkName>${namespace}/r0 </ChildLinkName>
            <translational_spring_constant>10 10 50</translational_spring_constant>
            <translational_damper_constant>5 5 20</translational_damper_constant>
            <rotational_spring_constant>8 15 8</rotational_spring_constant>
            <rotational_damper_constant>1 1 1</rotational_damper_constant>
          </plugin>
        </gazebo> -->

      </xacro:macro>

    </robot>
